CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,

    CONSTRAINT users_pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description     TEXT NOT NULL,
    requestor_id    BIGINT NOT NULL,
    created         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT requests_pk PRIMARY KEY (id),
    CONSTRAINT requests_requestor_fk FOREIGN KEY (requestor_id) REFERENCES users (id)
);


CREATE TABLE IF NOT EXISTS items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name            VARCHAR(100) NOT NULL,
    description     TEXT NOT NULL,
    available       BOOLEAN NOT NULL,

    user_id         BIGINT NOT NULL,
    request_id      BIGINT,

    CONSTRAINT items_pk PRIMARY KEY (id),
    CONSTRAINT items_user_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT items_request_fk FOREIGN KEY (request_id) REFERENCES requests (id)
);


CREATE TABLE IF NOT EXISTS bookings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,

    start_date      TIMESTAMP NOT NULL,
    end_date        TIMESTAMP NOT NULL,

    item_id         BIGINT NOT NULL,
    booker_id       BIGINT NOT NULL,

    status          VARCHAR(20) NOT NULL,

    CONSTRAINT bookings_pk PRIMARY KEY (id),
    CONSTRAINT bookings_item_fk FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT bookings_booker_fk FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT bookings_dates_chk CHECK (end_date > start_date)
);


CREATE TABLE IF NOT EXISTS comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text            TEXT NOT NULL,

    item_id         BIGINT NOT NULL,
    author_id       BIGINT NOT NULL,

    created         TIMESTAMP NOT NULL,

    CONSTRAINT comments_pk PRIMARY KEY (id),
    CONSTRAINT comments_item_fk FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT comments_author_fk FOREIGN KEY (author_id) REFERENCES users (id)
);